# Notebook 02: Análisis exploratorio de datos PM2.5

## Proyecto ambiental – Métodos Numéricos

En este notebook se realiza el análisis exploratorio de la base de datos ambiental correspondiente al material particulado PM2.5 en municipios de la Sabana Occidente de Cundinamarca.

El objetivo es aplicar herramientas de análisis de datos mediante pandas para identificar patrones, diferencias entre municipios, comportamiento de variables meteorológicas y posibles relaciones con la concentración de PM2.5.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/datos_pm25_sabana.csv")

df

,fecha,hora,municipio,punto_muestreo,pm25,temperatura,humedad,viento,calidad_aire,fuente_contaminante
0,19/05/2026,8:00 a.m.,Mosquera,Sector Industrial Celta,33.8,18.9,68,1.5,Moderada,Transporte de carga e industria
1,19/05/2026,10:00 a.m.,Funza,Parque Industrial San Diego,31.4,18.5,69,1.7,Moderada,Actividad industrial
2,19/05/2026,1:00 p.m.,Madrid,Variante Madrid - Centro,25.1,17.8,73,2.2,Aceptable,Tráfico vehicular
3,19/05/2026,3:00 p.m.,Facatativa,Sector Cartagenita,20.2,17.1,77,2.9,Aceptable,Zona urbana
4,21/05/2026,8:00 a.m.,Mosquera,Sector Industrial Celta,34.6,19.0,67,1.4,Moderada,Industria y vehículos pesados
5,21/05/2026,10:00 a.m.,Funza,Parque Industrial San Diego,32.1,18.7,68,1.6,Moderada,Centros logísticos
6,21/05/2026,1:00 p.m.,Madrid,Variante Madrid - Centro,24.8,18.0,72,2.3,Aceptable,Flujo vehicular
7,21/05/2026,3:00 p.m.,Facatativa,Sector Cartagenita,19.7,17.2,76,3.0,Buena,Baja actividad industrial
8,23/05/2026,8:00 a.m.,Mosquera,Sector Industrial Celta,35.3,18.7,69,1.3,Moderada,Transporte industrial
9,23/05/2026,10:00 a.m.,Funza,Parque Industrial San Diego,33.5,18.4,70,1.5,Moderada,Actividad logística
10,23/05/2026,1:00 p.m.,Madrid,Variante Madrid - Centro,26.0,17.7,74,2.1,Aceptable,Tráfico urbano
11,23/05/2026,3:00 p.m.,Facatativa,Sector Cartagenita,20.8,17.0,78,2.8,Aceptable,Zona residencial

## Promedio de PM2.5 por municipio

Se calcula el promedio de concentración de PM2.5 para cada municipio analizado.

In [3]:
df.groupby("municipio")["pm25"].mean()

municipio
Facatativa    20.233333
Funza         32.333333
Madrid        25.300000
Mosquera      34.566667
Name: pm25, dtype: float64

## Interpretación ambiental

Los municipios con mayores concentraciones promedio de PM2.5 presentan una mayor influencia de actividades industriales y tráfico vehicular.

Mosquera y Funza registran los valores más altos debido a la presencia de corredores industriales y logísticos. Por otro lado, Facatativá presenta menores concentraciones gracias a mejores condiciones de ventilación atmosférica y menor presión industrial.

## Temperatura promedio por municipio

In [4]:
df.groupby("municipio")["temperatura"].mean()

municipio
Facatativa    17.100000
Funza         18.533333
Madrid        17.833333
Mosquera      18.866667
Name: temperatura, dtype: float64

## Humedad relativa promedio por municipio

In [5]:
df.groupby("municipio")["humedad"].mean()

municipio
Facatativa    77.0
Funza         69.0
Madrid        73.0
Mosquera      68.0
Name: humedad, dtype: float64

## Velocidad promedio del viento

In [6]:
df.groupby("municipio")["viento"].mean()

municipio
Facatativa    2.9
Funza         1.6
Madrid        2.2
Mosquera      1.4
Name: viento, dtype: float64

## Filtrar municipios con PM2.5 alto

Se identifican registros con concentraciones superiores a 32 µg/m³.

In [7]:
df[df["pm25"] > 32]

,fecha,hora,municipio,punto_muestreo,pm25,temperatura,humedad,viento,calidad_aire,fuente_contaminante
0,19/05/2026,8:00 a.m.,Mosquera,Sector Industrial Celta,33.8,18.9,68,1.5,Moderada,Transporte de carga e industria
4,21/05/2026,8:00 a.m.,Mosquera,Sector Industrial Celta,34.6,19.0,67,1.4,Moderada,Industria y vehículos pesados
5,21/05/2026,10:00 a.m.,Funza,Parque Industrial San Diego,32.1,18.7,68,1.6,Moderada,Centros logísticos
8,23/05/2026,8:00 a.m.,Mosquera,Sector Industrial Celta,35.3,18.7,69,1.3,Moderada,Transporte industrial
9,23/05/2026,10:00 a.m.,Funza,Parque Industrial San Diego,33.5,18.4,70,1.5,Moderada,Actividad logística

## Interpretación del filtro

Los registros con mayores concentraciones de PM2.5 corresponden principalmente a Mosquera y Funza, municipios caracterizados por una fuerte actividad industrial y tránsito de vehículos de carga.

## Aplicación de condicionales

Se crea una nueva columna para clasificar el nivel de contaminación atmosférica según la concentración de PM2.5.

In [8]:
def clasificar_pm25(valor):
    
    if valor <= 12:
        return "Buena"
    
    elif valor <= 35:
        return "Moderada"
    
    else:
        return "Dañina"


df["clasificacion_pm25"] = df["pm25"].apply(clasificar_pm25)

df

,fecha,hora,municipio,punto_muestreo,pm25,temperatura,humedad,viento,calidad_aire,fuente_contaminante,clasificacion_pm25
0,19/05/2026,8:00 a.m.,Mosquera,Sector Industrial Celta,33.8,18.9,68,1.5,Moderada,Transporte de carga e industria,Moderada
1,19/05/2026,10:00 a.m.,Funza,Parque Industrial San Diego,31.4,18.5,69,1.7,Moderada,Actividad industrial,Moderada
2,19/05/2026,1:00 p.m.,Madrid,Variante Madrid - Centro,25.1,17.8,73,2.2,Aceptable,Tráfico vehicular,Moderada
3,19/05/2026,3:00 p.m.,Facatativa,Sector Cartagenita,20.2,17.1,77,2.9,Aceptable,Zona urbana,Moderada
4,21/05/2026,8:00 a.m.,Mosquera,Sector Industrial Celta,34.6,19.0,67,1.4,Moderada,Industria y vehículos pesados,Moderada
5,21/05/2026,10:00 a.m.,Funza,Parque Industrial San Diego,32.1,18.7,68,1.6,Moderada,Centros logísticos,Moderada
6,21/05/2026,1:00 p.m.,Madrid,Variante Madrid - Centro,24.8,18.0,72,2.3,Aceptable,Flujo vehicular,Moderada
7,21/05/2026,3:00 p.m.,Facatativa,Sector Cartagenita,19.7,17.2,76,3.0,Buena,Baja actividad industrial,Moderada
8,23/05/2026,8:00 a.m.,Mosquera,Sector Industrial Celta,35.3,18.7,69,1.3,Moderada,Transporte industrial,Dañina
9,23/05/2026,10:00 a.m.,Funza,Parque Industrial San Diego,33.5,18.4,70,1.5,Moderada,Actividad logística,Moderada
10,23/05/2026,1:00 p.m.,Madrid,Variante Madrid - Centro,26.0,17.7,74,2.1,Aceptable,Tráfico urbano,Moderada
11,23/05/2026,3:00 p.m.,Facatativa,Sector Cartagenita,20.8,17.0,78,2.8,Aceptable,Zona residencial,Moderada

## Conteo de clasificación de calidad del aire

In [9]:
df["clasificacion_pm25"].value_counts()

clasificacion_pm25
Moderada    11
Dañina       1
Name: count, dtype: int64

## Tabla resumen del proyecto

Se genera una tabla resumen con los promedios ambientales por municipio.

In [10]:
tabla_resumen = df.groupby("municipio")[["pm25","temperatura","humedad","viento"]].mean()

tabla_resumen

                 pm25  temperatura  humedad  viento
municipio
Facatativa  20.233333    17.100000     77.0     2.9
Funza       32.333333    18.533333     69.0     1.6
Madrid      25.300000    17.833333     73.0     2.2
Mosquera    34.566667    18.866667     68.0     1.4